# Generated by Django 3.1 on 2020-11-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_date', models.DateTimeField(blank=True, null=True)),
                ('selling_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('id_order', models.IntegerField(blank=True, null=True)),
                ('id_pea', models.IntegerField(blank=True, null=True)),
                ('name_pea', models.CharField(blank=True, max_length=200, null=True)),
                ('id_asset', models.CharField(blank=True, max_length=70, null=True)),
                ('name_asset', models.CharField(blank=True, max_length=200, null=True)),
                ('type_asset', models.CharField(blank=True, max_length=10, null=True)),
                ('initial_amount', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('live', models.IntegerField(blank=True, null=True)),
                ('risk', models.IntegerField(blank=True, null=True)),
                ('global_variation', models.FloatField(blank=True, null=True)),
                ('interday_variation', models.FloatField(blank=True, null=True)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PEA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('id_pea', models.IntegerField(blank=True, null=True)),
                ('name_pea', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('initial_amount', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('risk', models.IntegerField(blank=True, null=True)),
                ('global_variation', models.FloatField(blank=True, null=True)),
                ('interday_variation', models.FloatField(blank=True, null=True)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PEAHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('id_pea', models.IntegerField(blank=True, null=True)),
                ('name_pea', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('risk', models.IntegerField(blank=True, null=True)),
                ('global_variation', models.FloatField(blank=True, null=True)),
                ('interday_variation', models.FloatField(blank=True, null=True)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
