# Generated by Django 3.1 on 2020-11-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pea',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='peahistory',
            options={'managed': True},
        ),
    ]
