# Generated by Django 2.2.7 on 2019-11-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pea',
            old_name='name_asset',
            new_name='id_asset',
        ),
    ]
