# Generated by Django 2.2.7 on 2019-11-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0002_auto_20191129_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pea',
            old_name='id_investment',
            new_name='id_pea',
        ),
    ]
