# Generated by Django 2.2.7 on 2019-11-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0003_auto_20191129_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_date', models.DateTimeField(blank=True, null=True)),
                ('selling_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('id_pea', models.FloatField(blank=True, null=True)),
                ('id_asset', models.CharField(blank=True, max_length=70, null=True)),
                ('initial_amount', models.FloatField(blank=True, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pea',
            old_name='initial_amount',
            new_name='name_pea',
        ),
        migrations.RemoveField(
            model_name='pea',
            name='buying_date',
        ),
        migrations.RemoveField(
            model_name='pea',
            name='id_asset',
        ),
        migrations.RemoveField(
            model_name='pea',
            name='selling_date',
        ),
    ]
