# Generated by Django 2.2.7 on 2019-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0004_auto_20191129_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='pea',
            name='risk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_pea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pea',
            name='currency',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pea',
            name='id_pea',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
