# Generated by Django 2.2.7 on 2019-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0005_auto_20191129_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name_pea',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
