# Generated by Django 2.2.7 on 2019-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0006_auto_20191129_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name_pea',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pea',
            name='name_pea',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
