# Generated by Django 2.2.7 on 2019-11-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0007_auto_20191129_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='live',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
