# Generated by Django 2.2.7 on 2019-12-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0010_pea_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='risk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
