# Generated by Django 2.2.7 on 2019-12-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0012_pea_varation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pea',
            old_name='varation',
            new_name='variation',
        ),
    ]
