# Generated by Django 2.2.7 on 2019-12-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0013_auto_20191205_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='pea',
            name='initial_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
