# Generated by Django 2.2.7 on 2019-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0014_pea_initial_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pea',
            old_name='variation',
            new_name='global_variation',
        ),
        migrations.AddField(
            model_name='order',
            name='global_variation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='interday_variation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pea',
            name='interday_variation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
