# Generated by Django 2.2.7 on 2019-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0015_auto_20191205_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='peahistory',
            name='global_variation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peahistory',
            name='interday_variation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
