# Generated by Django 2.2.7 on 2019-12-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pea', '0016_auto_20191205_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_asset',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type_asset',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
