from assets.scripts.quantpy.portfolio import Portfolio

# Test:
"""
https://stackoverflow.com/questions/38967533/retrieve-company-name-with-ticker-symbol-input-yahoo-or-google-api
https://quant.stackexchange.com/questions/26162/where-can-i-get-a-list-of-all-yahoo-finance-stocks-symbols
https://pypi.org/project/Yahoo-ticker-downloader/
"""

SYMBOL_CONVERTER_DICT = {'alstom',
 'nexans',
 'nexity',
 'claranova',
 'lisi',
 'bureau veritas',
 'adocia',
 'latecoere',
 'publicis grp',
 'metabolic expl.',
 'hsbc hldg',
 'lexibook linguist',
 'lna sante',
 'pernod ricard',
 'fdj',
 'arkema',
 'pierre et vacances',
 'futuren',
 'lacie s.a.',
 'dms',
 'artmarket.com',
 'nanobiotix',
 'quadient',
 'scor',
 'technip',
 'elior group',
 'geci intl',
 'natixis',
 'haulotte group',
 'saint-gobain',
 'manitou bf',
 'sequana regpt',
 'wavestone',
 'sartorius sted',
 'total',
 'seloger.com',
 'eurazeo',
 'financiere odet',
 'derichebourg',
 'bull regroupement',
 'seche environ',
 'genfit',
 'aubay',
 'verimatrix',
 'altran techno.',
 'solocal',
 'ffp',
 'gl events',
 'bollore',
 'delachaux',
 'plast val de loire',
 'air france - klm',
 'capgemini',
 'marie brizard',
 'modelabs group',
 'casino guic per',
 'orange',
 'nicox',
 'anf immobilier',
 'plast v de loir',
 'chargeurs',
 'lagardere',
 'areva',
 'siph',
 'wendel',
 'eramet',
 'orpea',
 'euro disney',
 'technipfmc',
 'axa',
 'lumibird',
 'sopra steria',
 'bigben interactiv',
 'cie des alpes',
 'gameloft',
 'savencia',
 'worldline',
 'april',
 'eiffage',
 'getlink (ex: eurotunnel)',
 'dbv techno',
 'valeo',
 'euronext',
 'colas',
 'innate pharma',
 'suez',
 'trigano',
 'gfi informatique',
 'oeneo',
 'canal plus (ste ed)',
 'essilorluxott',
 'atos',
 'ipsos',
 'hermes intl',
 "l'oreal",
 'le belier',
 'beneteau',
 'atari',
 'transgene',
 'medica',
 'erytech pharma',
 'laurent perrier',
 'eutelsat communic.',
 'christian dior',
 'sanofi',
 'montupet',
 'faurecia',
 'id logistics',
 'ipsen',
 'gaztrans.techn.',
 'ald',
 'societe generale',
 'sqli regpt',
 'stallergenes',
 'stentys',
 'vicat',
 'imerys',
 'aprr (autoroutes prr)',
 'affine r',
 'remy cointreau',
 'bouygues',
 'ses imagotag',
 'actia group',
 'synergie',
 'ubisoft entertain.',
 'stef',
 'europ m grp',
 'lvmh moet vuitton',
 'blue solutions',
 'vinci',
 'akka technologies',
 'soitec',
 'coface',
 'valneva',
 'esso',
 'naturex',
 'havas',
 'edenred',
 'seb',
 'ramsay generale',
 'tf1',
 'edf',
 'legrand',
 'veolia environnem',
 'groupe gorge',
 'sword group',
 'faiveley transport',
 'mersen',
 'assystem  (ex assystem brime)',
 'bnp paribas',
 'bourbon corp.',
 'danone',
 'mauna kea tech',
 'cgg',
 'akwel',
 'guyenne gascogne',
 'jacquet metal sce',
 'lvl medical groupe',
 'rothschild & co',
 'europacorp',
 'fnac darty',
 'safran',
 'prologue',
 'axway software',
 'onxeo',
 'pharmagest interact',
 'vallourec',
 'dassault avia',
 'jcdecaux sa.',
 'boiron',
 'rubis',
 'airbus',
 'kering (ex: ppr)',
 'vranken-pommery monopole',
 'entrepose contracting',
 'metropole tele',
 'groupe ldlc',
 'alten',
 'eurofins scientif',
 'schneider el',
 'teleperformance',
 'tff group',
 'archos',
 'credit agricole sa',
 'interparfums',
 'maurel & prom',
 'accor',
 'thales',
 'rexel',
 'rue du commerce',
 'altamir',
 'adp',
 'altarea',
 'spie',
 'cegedim',
 'rallye',
 'psb industries',
 'crit',
 'technicolor',
 'bonduelle',
 'virbac',
 'cnp assurances',
 'manutan intl',
 'argan',
 'catering intl cis',
 'medtech',
 'michelin n',
 'iliad',
 'euler hermes',
 'rhodia',
 'renault',
 'rio tinto ord',
 'ekinops',
 'recylex',
 'cnim group',
 'vivendi',
 'korian',
 'abc arbitrage',
 'fimalac',
 'vilmorin & cie',
 'carrefour',
 'hexaom',
 'ginger',
 'peugeot',
 'sodexo',
 'xpo logistics',
 'air liquide',
 'eos imaging',
 'ab science',
 'nokia',
 'albioma',
 'bic(societe)',
 'engie',
 'lectra',
 'valtech rev.split',
 'dassault systemes',
 'stmicroelectr',
 'ingenico group',
 'plastic omnium',
 'cic',
 'biomerieux',
 'exel industries a',
 'neopost',
 'EURAZEO',
 'TRIGANO',
 'EULER HERMES',
 'TRANSGENE',
 'BIGBEN INTERACTIVE',
 'KERING',
 'ALD',
 'AB SCIENCE',
 'ADOCIA',
 'CNIM GROUP',
 'SOCIETE GENERALE',
 'ELIOR GROUP',
 'CHARGEURS',
 'ILIAD',
 'SQLI',
 'EXEL INDUSTRIES A',
 'LACIE S.A.',
 'LVMH MOET VUITTON',
 'MEDTECH',
 'WENDEL',
 'FNAC DARTY',
 'SPIE',
 'WAVESTONE',
 'ATARI',
 'ESSO',
 'JCDECAUX SA.',
 'RALLYE',
 'TOTAL',
 'GFI INFORMATIQUE',
 'AIR LIQUIDE',
 'ADP',
 'BNP PARIBAS',
 'TECHNIP',
 'IPSEN',
 'BENETEAU',
 'EKINOPS',
 'AKWEL',
 'FINANCIERE ODET',
 'FIMALAC',
 'BOUYGUES',
 'MANUTAN INTL',
 'CATERING INTL CIS',
 'CRIT',
 'METROPOLE TELE',
 'BOURBON CORP.',
 'ORPEA',
 'SCOR',
 'SARTORIUS STEDIM BIOTECH',
 'EUROFINS SCIENTIF',
 'ANF IMMOBILIER',
 'EOS IMAGING',
 'MODELABS GROUP',
 'QUADIENT',
 'LE BELIER',
 'CASINO GUIC PER',
 'VALTECH',
 'MERSEN',
 'SAVENCIA',
 'ALTAREA',
 'SOLOCAL',
 'NEXITY',
 'NATIXIS',
 'AIR FRANCE - KLM',
 'LISI',
 'BOIRON',
 'ACCOR',
 'FFP',
 'CAPGEMINI',
 'IMERYS',
 'DMS',
 'FUTUREN',
 'ASSYSTEM  (EX ASSYSTEM BRIME)',
 'LEXIBOOK LINGUIST',
 'MANITOU BF',
 'EUTELSAT COMMUNIC.',
 'MAUNA KEA TECH',
 'SEB',
 'CEGEDIM',
 'AUBAY',
 'EUROPCAR MOBILITY GRP',
 'AXWAY SOFTWARE',
 'CIE DES ALPES',
 'HAVAS',
 'STMICROELECTRONICS',
 'GENFIT',
 'VERIMATRIX',
 'NICOX',
 'TF1',
 'ACTIA GROUP',
 'ARGAN',
 'RAMSAY GENERALE',
 'REXEL',
 'PLASTiVALOIRE',
 'INGENICO GROUP',
 'VALNEVA',
 'ALBIOMA',
 'GAMELOFT',
 'COFACE',
 'SAFRAN',
 'OENEO',
 'FDJ',
 'HSBC HOLDINGS',
 "L'OREAL",
 'EDENRED',
 'EIFFAGE',
 'CNP ASSURANCES',
 'CARREFOUR',
 'RIO TINTO ORD',
 'RECYLEX',
 'FAIVELEY TRANSPORT',
 'SYNERGIE',
 'XPO LOGISTICS',
 'SOPRA STERIA',
 'BUREAU VERITAS',
 'NATUREX',
 'MARIE BRIZARD',
 'CHRISTIAN DIOR',
 'NANOBIOTIX',
 'GUYENNE GASCOGNE',
 'TFF GROUP',
 'SANOFI',
 'CGG',
 'MEDICA',
 'GETLINK (ex: EUROTUNNEL)',
 'IPSOS',
 'SODEXO',
 'ERYTECH PHARMA',
 'SES IMAGOTAG',
 'TELEPERFORMANCE',
 'INNATE PHARMA',
 'PLAST V DE LOIR',
 'ENTREPOSE CONTRACTING',
 'SAINT-GOBAIN',
 'ERAMET',
 'REMY COINTREAU',
 'ESSILORLUXOTTICA',
 'KORIAN',
 'MONTUPET',
 'CANAL PLUS (STE ED)',
 'GAZTRANS.TECHN.',
 'ARKEMA',
 'EDF',
 'STEF',
 'GECI INTL',
 'PLASTIC OMNIUM',
 'SIPH',
 'BIOMERIEUX',
 'LEGRAND',
 'BONDUELLE',
 'LATECOERE',
 'ONXEO',
 'MICHELIN N',
 'VALEO',
 'ARTMARKET.COM',
 'SWORD GROUP',
 'SOITEC',
 'SUEZ',
 'MAUREL & PROM',
 'VEOLIA ENVIRONNEM',
 'APRIL',
 'GINGER',
 'APRR (AUTOROUTES PRR)',
 'GL EVENTS',
 'PERNOD RICARD',
 'GROUPE GORGE',
 'HAULOTTE GROUP',
 'LAURENT PERRIER',
 'NOKIA',
 'AKKA TECHNOLOGIES',
 'EURONEXT',
 'LAGARDERE',
 'STENTYS',
 'CLARANOVA',
 'TECHNIPFMC',
 'LUMIBIRD',
 'DASSAULT SYSTEMES',
 'BLUE SOLUTIONS',
 'JACQUET METAL SCE',
 'THALES',
 'RUBIS',
 'ORANGE',
 'VINCI',
 'VIVENDI',
 'ID LOGISTICS',
 'BIC',
 'STALLERGENES',
 'ROTHSCHILD & CO',
 'ENGIE',
 'NEXANS',
 'PEUGEOT',
 'EUROPACORP',
 'PIERRE ET VACANCES',
 'VILMORIN & CIE',
 'LNA SANTE',
 'PHARMAGEST INTERACT',
 'LECTRA',
 'DASSAULT AVIATION',
 'SECHE ENVIRON',
 'HEXAOM',
 'HERMES INTL'}
