# Generated by Django 2.2.7 on 2019-11-25 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fundsCA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('date_dernier_cours', models.DateTimeField(blank=True, null=True)),
                ('id_fund', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_id', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('variation', models.FloatField(blank=True, null=True)),
                ('risk_level', models.IntegerField(blank=True, null=True)),
                ('net_asset', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
