# Generated by Django 2.2.7 on 2019-11-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds_CA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundsca',
            name='id_fund',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
