# Generated by Django 3.1 on 2020-11-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds_CA', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundsca',
            options={'managed': True},
        ),
    ]
