# Generated by Django 3.1 on 2020-11-08 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfosSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('codePostal', models.IntegerField(blank=True, null=True)),
                ('surface', models.IntegerField(blank=True, null=True)),
                ('prix_m2_max', models.FloatField(blank=True, null=True)),
                ('vente', models.FloatField(blank=True, null=True)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
