# Generated by Django 2.1.7 on 2019-03-25 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfosSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('codePostal', models.IntegerField(blank=True, null=True)),
                ('surface', models.IntegerField(blank=True, null=True)),
                ('prix_m2_max', models.FloatField(blank=True, null=True)),
                ('vente', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
