# Generated by Django 2.1.7 on 2019-04-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfossaved',
            name='user_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
