# Generated by Django 2.1.7 on 2019-04-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfossaved_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfossaved',
            old_name='user_id',
            new_name='user_username',
        ),
    ]
