# Generated by Django 2.2.7 on 2019-12-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='date_dernier_cours',
        ),
    ]
