# Generated by Django 3.1 on 2020-11-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimAssetsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('id_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange', models.CharField(blank=True, max_length=5, null=True)),
                ('shortname', models.CharField(blank=True, max_length=100, null=True)),
                ('quoteType', models.CharField(blank=True, max_length=10, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('index', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('typeDisp', models.CharField(blank=True, max_length=10, null=True)),
                ('longname', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('betas', models.FloatField(blank=True, null=True)),
                ('weight_low_var', models.FloatField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('variation', models.FloatField(blank=True, null=True)),
                ('dividende', models.FloatField(blank=True, null=True)),
                ('value_3_month', models.FloatField(blank=True, null=True)),
                ('value_1_month', models.FloatField(blank=True, null=True)),
                ('value_1_week', models.FloatField(blank=True, null=True)),
                ('var_3_month', models.FloatField(blank=True, null=True)),
                ('var_1_month', models.FloatField(blank=True, null=True)),
                ('var_1_week', models.FloatField(blank=True, null=True)),
                ('previously_selected', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
