# Generated by Django 3.1 on 2020-11-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_optimassetsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimassetsinfo',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optimassetsinfo',
            name='previously_selected',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
