# Generated by Django 2.1.7 on 2020-03-27 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_assets_date_dernier_cours'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('id_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('variation', models.FloatField(blank=True, null=True)),
                ('dividende', models.FloatField(blank=True, null=True)),
                ('value_3_month', models.FloatField(blank=True, null=True)),
                ('value_1_month', models.FloatField(blank=True, null=True)),
                ('value_1_week', models.FloatField(blank=True, null=True)),
                ('var_3_month', models.FloatField(blank=True, null=True)),
                ('var_1_month', models.FloatField(blank=True, null=True)),
                ('var_1_week', models.FloatField(blank=True, null=True)),
                ('value_over_3_months', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
