# Generated by Django 2.1.7 on 2020-03-27 20:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsinfo',
            name='value_over_3_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
