# Generated by Django 3.1 on 2020-11-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20201108_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsinfo',
            name='date_dividende',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='assetsinfo',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
