# Generated by Django 2.1.7 on 2020-03-27 20:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200327_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsinfo',
            name='date_over_3_months',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
