# Generated by Django 3.1 on 2020-11-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetsinfo_asset_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsinfo',
            name='longname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assetsinfo',
            name='symbol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
