# Generated by Django 3.1 on 2020-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20201126_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsCheckLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('id_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('longname', models.CharField(blank=True, max_length=100, null=True)),
                ('down_limit', models.FloatField(blank=True, null=True)),
                ('up_limit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='assetsinfo',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
