# Generated by Django 3.1 on 2020-11-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20201127_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetschecklimits',
            name='down_limit_knocked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetschecklimits',
            name='up_limit_knocked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
