# Generated by Django 3.1 on 2020-12-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_optimassetsinfo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedAssetsToBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('id_asset', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_objective', models.FloatField(blank=True, null=True)),
                ('potential_percent', models.FloatField(blank=True, null=True)),
                ('nb_analysts', models.IntegerField(blank=True, null=True)),
                ('net_benefit_in_eur', models.FloatField(blank=True, null=True)),
                ('rentability_n_percent', models.FloatField(blank=True, null=True)),
                ('price_earning_ratio_n', models.FloatField(blank=True, null=True)),
                ('price_earning_ratio_n_plus_1', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
