# Generated by Django 3.1 on 2020-12-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_recommendedassetstobuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedassetstobuy',
            name='date_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
