# Generated by Django 3.1 on 2020-12-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_auto_20201220_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetschecklimits',
            name='potential_percent',
        ),
    ]
