# Generated by Django 3.1 on 2020-12-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_remove_assetschecklimits_potential_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetschecklimits',
            name='potential_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
